import test from 'node:test';
import assert from 'node:assert/strict';
import {score,shuffledShoe,newGame,playerAction,dealerAction,legalDealer,publicState,setMode} from '../lib/blackjack.mjs';
const card=rank=>({rank,suit:'spades'});
const hand=ranks=>ranks.map(card);
function setup(draws){const g=newGame('test-table');g.mode='grok';g.deck=[...Array.from({length:60},()=>card('2')),...hand(draws).reverse()];return g;}
test('aces retain the best non-busting value',()=>{for(const ranks of [['A','A','9'],['A','A','9','10'],['A','K','K']])assert.equal(score(hand(ranks)).total,21);assert.equal(score(hand(['A','K','K','10'])).total,31);});
test('shoe contains six copies of each card',()=>{const d=shuffledShoe();assert.equal(d.length,312);const counts=new Map();for(const c of d){const k=c.rank+c.suit;counts.set(k,(counts.get(k)||0)+1);}assert.equal(counts.size,52);assert.ok([...counts.values()].every(n=>n===6));});
test('natural blackjack pays 3:2, including half chips',()=>{const g=setup(['A','9','K','10']);playerAction(g,'deal',25);assert.equal(g.bankroll,1037.5);assert.equal(g.outcome.profit,37.5);assert.equal(g.phase,'settled');});
test('both naturals push and dealer natural resolves before play',()=>{const g=setup(['A','A','K','Q']);playerAction(g,'deal',25);assert.equal(g.bankroll,1000);assert.equal(g.outcome.result,'push');const d=setup(['10','A','9','K']);playerAction(d,'deal',25);assert.equal(d.phase,'settled');assert.throws(()=>playerAction(d,'double'));});
test('dealer hits 16 and stands on soft 17',()=>{const g=setup(['10','A','8','5','A']);playerAction(g,'deal',25);playerAction(g,'stand');assert.deepEqual(legalDealer(g),['hit']);assert.throws(()=>dealerAction(g,'stand'));dealerAction(g,'hit');assert.deepEqual(legalDealer(g),['stand']);assert.throws(()=>dealerAction(g,'hit'));dealerAction(g,'stand');assert.equal(g.outcome.result,'win');});
test('double takes one card and uses the doubled stake',()=>{const g=setup(['5','10','6','7','K']);playerAction(g,'deal',25);playerAction(g,'double');assert.equal(g.bet,50);assert.equal(g.bankroll,950);assert.equal(g.player.length,3);assert.equal(g.phase,'dealer');dealerAction(g,'stand');assert.equal(g.bankroll,1050);assert.throws(()=>playerAction(g,'double'));});
test('player bust settles once and blocks all dealer actions',()=>{const g=setup(['K','10','9','7','5']);playerAction(g,'deal',25);playerAction(g,'hit');assert.equal(g.phase,'settled');assert.equal(g.bankroll,975);assert.throws(()=>dealerAction(g,'stand'));assert.equal(g.hands,1);});
test('public state redacts the hole card and entire shoe',()=>{const g=setup(['10','6','7','Q']);playerAction(g,'deal',25);const s=publicState(g);assert.deepEqual(s.dealer,[card('6'),{hidden:true}]);assert.equal(s.dealerScore.total,6);assert.ok(!('deck'in s));assert.ok(!('dealerToken'in s));playerAction(g,'stand');assert.equal(publicState(g).dealer[1].rank,'Q');});
test('invalid wagers and unavailable double are rejected',()=>{for(const b of [-1,0,4,501,10.5,'25',NaN,Infinity])assert.throws(()=>playerAction(setup(['9','7','8','9']),'deal',b));const g=setup(['2','10','3','7','4']);playerAction(g,'deal',25);playerAction(g,'hit');assert.throws(()=>playerAction(g,'double'));assert.throws(()=>playerAction(g,'split'));});
test('switch to house completes a waiting dealer turn',()=>{const g=setup(['10','6','8','10','K']);playerAction(g,'deal',25);playerAction(g,'stand');setMode(g,'house');assert.equal(g.phase,'settled');assert.equal(g.bankroll,1025);});
