"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowUpRight,ArrowUp,Check,Copy,Plug,MessageCircle,RotateCcw,X,Info,ChevronDown,Send,Spade} from "lucide-react";

type Card={rank?:string;suit?:string;hidden?:boolean};
type State={id:string;revision:number;round:number;bankroll:number;bet:number;phase:string;mode:string;dealerName:string;player:Card[];dealer:Card[];playerScore:{total:number;soft:boolean};dealerScore:{total:number;soft:boolean};outcome:null|{result:string;reason:string;profit:number};messages:{id:string;role:string;name:string;text:string;at:number}[];history:{round:number;result:string;profit:number;player:number;dealer:number}[];wins:number;hands:number;legalPlayerActions:string[];legalDealerActions:string[];botSeen:number|null;dealerToken?:string;nextStep:string};
const chipFormat=(n:number)=>n.toLocaleString(undefined,{maximumFractionDigits:1});
const suits:Record<string,string>={spades:"♠",hearts:"♥",diamonds:"♦",clubs:"♣"};
const instructions="Use the After Hours blackjack connector to join my table as dealer. Call get_table, then join_table once with your name. Read the latest player messages and reply using post_chat so I can see you in the game. Follow legalDealerActions with dealer_action until the dealer turn is finished. The server controls the cards and payouts. When waiting for me, stop. Whenever I say Continue, read the latest table and chat before acting again. Keep your personality and talk to me at the table.";
function PlayingCard({card,index}:{card:Card;index:number}){if(card.hidden)return <div className="playing-card back" aria-label="Face-down dealer card" style={{animationDelay:index*60+"ms"}}>♠</div>;return <div className={"playing-card face "+(["hearts","diamonds"].includes(card.suit??"")?"red":"")} aria-label={card.rank+" of "+card.suit} style={{animationDelay:index*60+"ms"}}><span className="card-corner">{card.rank}<b>{suits[card.suit??""]}</b></span><span className="card-suit">{suits[card.suit??""]}</span><span className="card-corner bottom">{card.rank}<b>{suits[card.suit??""]}</b></span></div>}
export default function Home(){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[bet,setBet]=useState(25),[draft,setDraft]=useState(""),[modal,setModal]=useState<null|"connect"|"rules">(null),[tab,setTab]=useState("mcp"),[dealerToken,setDealerToken]=useState(""),[copied,setCopied]=useState(""),[bridge,setBridge]=useState(""),[bridgePrompt,setBridgePrompt]=useState(""),[connecting,setConnecting]=useState(false),[online,setOnline]=useState(true);
 const log=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),stateRef=useRef<State|null>(null),locked=useRef(false),modalTrigger=useRef<HTMLElement|null>(null);
 function receive(next:State){const {dealerToken:incoming,...clean}=next;try{if(incoming)sessionStorage.setItem('ah-dealer-'+next.id,incoming);const saved=incoming||sessionStorage.getItem('ah-dealer-'+next.id);if(saved)setDealerToken(saved);}catch{if(incoming)setDealerToken(incoming);}if(!stateRef.current||next.revision>=stateRef.current.revision){stateRef.current=clean;setState(clean);}}
 async function request(payload?:Record<string,unknown>){const r=await fetch("/api/table",{method:payload?"POST":"GET",headers:payload?{"Content-Type":"application/json"}:undefined,body:payload?JSON.stringify(payload):undefined,cache:"no-store"});const data=await r.json() as State & {error?:string;dealerToken:string};if(!r.ok)throw new Error(data.error??"The table could not be reached.");return data;}
 async function refresh(){try{receive(await request());setOnline(true);}catch{setOnline(false);}}
 useEffect(()=>{let alive=true;request().then(s=>{if(alive)receive(s)}).catch(()=>{});return()=>{alive=false}},[]);
 useEffect(()=>{if(!state?.id)return;const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!locked.current)void refresh()},2500);const visible=()=>{if(document.visibilityState==="visible")void refresh()};document.addEventListener("visibilitychange",visible);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",visible)}},[state?.id]);
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:"smooth"})},[state?.messages.at(-1)?.id]);
 useEffect(()=>{if(modal){modalTrigger.current=document.activeElement as HTMLElement;dialog.current?.showModal()}else{dialog.current?.close();modalTrigger.current?.focus()}},[modal]);
 async function act(action:string,extras:Record<string,unknown>={}){if(locked.current)return false;locked.current=true;setBusy(true);setError("");try{receive(await request({action,expectedRevision:stateRef.current?.revision,...extras}));setOnline(true);return true;}catch(e){setError(e instanceof Error?e.message:"Something went wrong.");await refresh();return false;}finally{locked.current=false;setBusy(false)}}
 async function deal(){if(!state){if(await act("create"))await act("deal",{bet});}else await act("deal",{bet});}
 async function connect(){if(!state){if(!await act("create"))return;}setModal("connect");}
 async function copy(text:string,key:string){try{await navigator.clipboard.writeText(text);setCopied(key);setTimeout(()=>setCopied(""),2000)}catch{setError("Copy was blocked. Select and copy the text below.");}}
 async function rotate(){setConnecting(true);try{const r=await request({action:"connector"});setDealerToken(r.dealerToken);try{sessionStorage.setItem("ah-dealer-"+stateRef.current?.id,r.dealerToken)}catch{}setCopied("");}catch(e){setError((e as Error).message)}finally{setConnecting(false)}}
 function preparePrompt(){if(!state)return;const action=state.legalDealerActions[0]??"say";const p="You are my blackjack dealer. Keep your personality. Reply with ONE JSON object, no commentary outside it. Cards and rules are controlled by the game. If legalDealerActions is empty, use action say. Otherwise use the sole legal action. Use exactly this shape: "+JSON.stringify({gameId:state.id,expectedRevision:state.revision,action,message:"Your dealer dialogue here."})+"\nCurrent public table:\n"+JSON.stringify(state);setBridgePrompt(p);void copy(p,"prompt");}
 async function applyBridge(){try{const raw=bridge.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const reply=JSON.parse(raw);if(!reply||typeof reply!=="object"||!Number.isSafeInteger(reply.expectedRevision)||!["hit","stand","say"].includes(reply.action))throw new Error("Paste Grok’s JSON reply with gameId, expectedRevision, action, and message.");if(await act("bridge",{gameId:reply.gameId,expectedRevision:reply.expectedRevision,dealerAction:reply.action,message:reply.message}))setBridge("");}catch(e){setError((e as Error).message)}}
 const phase=state?.phase??"betting",canBet=phase==="betting"||phase==="settled",isGrok=state?.mode==="grok",balance=state?.bankroll??1000,legal=state?.legalPlayerActions??[],seen=state?.botSeen,botRecent=!!seen&&Date.now()-seen<30000;
 const connectorUrl=dealerToken&&typeof window!=="undefined"?window.location.origin+"/api/mcp/"+dealerToken:"";
 const outcome=state?.outcome;
 return <main className="app-shell">
 <header><a className="wordmark" href="/" aria-label="After Hours blackjack">♠ <span>AFTER HOURS<small>BLACKJACK CLUB</small></span></a><div className="header-actions"><span className="tag">PLAY CHIPS ONLY</span><button className="text-button" aria-label="Table rules" onClick={()=>setModal("rules")}><Info size={16}/> <span>Table rules</span></button></div></header>
 <section className="intro"><div><p className="eyebrow">THE TABLE IS YOURS</p><h1>A little luck. <em>A familiar dealer.</em></h1></div><button className="connect-button" onClick={connect} disabled={busy}><Plug size={17}/>{isGrok?"Grok connection":"Bring your Grok bot"}<ArrowUpRight size={16}/></button></section>
 {error&&<div className="error-banner" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError("")}><X size={16}/></button></div>}
 {!online&&state&&<div className="offline" role="status">Connection interrupted. Reconnecting to your table…</div>}
 <section className="game-layout">
 <div className="game-column"><div className="table-topline"><span><span className="tiny-spade">♠</span> BLACKJACK <span className="muted">/ TABLE {state?.id.slice(0,4).toUpperCase()??"01"}</span></span><span className="muted">HAND {String(state?.round??0).padStart(2,"0")}</span></div>
 <div className="table"><div className="table-inside">
 <div className="hand-label"><span>{state?.dealerName??"HOUSE DEALER"}</span>{!!state?.dealer.length&&<span className="score">{state.dealerScore.total}{state.dealer.some(c=>c.hidden)?" + ?":state.dealerScore.soft?" soft":""}</span>}</div>
 <div className="cards dealer-cards">{state?.dealer.length?state.dealer.map((card,i)=><PlayingCard key={state.round+"d"+i} card={card} index={i}/>):[0,1].map(i=><PlayingCard key={i} card={{hidden:true}} index={i}/>)}</div>
 <div className="table-brand" aria-hidden="true">AFTER HOURS<span>BLACKJACK PAYS 3:2</span><small>DEALER STANDS ON ALL 17s</small></div>
 <div className="table-status" aria-live="polite">{outcome?<><strong className={outcome.profit>0?"win":""}>{outcome.result==="blackjack"?"BLACKJACK":outcome.result==="win"?"YOU WIN":outcome.result==="push"?"PUSH":"DEALER WINS"}</strong><span>{outcome.profit>0?"+":""}{chipFormat(outcome.profit)} chips</span></>:phase==="dealer"?<><strong>DEALER’S TURN</strong><span>{isGrok?"Say “Continue” in Grok to play the dealer hand.":"Turning the cards…"}</span></>:phase==="player"?<><strong>YOUR MOVE</strong><span>Trust your hand. Hit, stand, or double.</span></>:<><strong>FEELING LUCKY?</strong><span>Choose a bet below. The next hand is yours.</span></>}</div>
 <div className="cards player-cards">{state?.player.length?state.player.map((card,i)=><PlayingCard key={state.round+"p"+i} card={card} index={i}/>):<><div className="empty-card"/><div className="empty-card"/></>}</div>
 <div className="hand-label player-label"><span>YOUR HAND</span>{!!state?.player.length&&<span className={"score "+(state.playerScore.total>21?"bust":"")}>{state.playerScore.total}{state.playerScore.soft?" soft":""}</span>}{!!state?.bet&&<span className="table-wager">{chipFormat(state.bet)} bet</span>}</div>
 </div></div>
 <div className="controls"><div className="bankroll"><span className="control-label">YOUR CHIPS</span><strong>{chipFormat(balance)} <small>◈</small></strong></div><div className="wager-controls"><label className="control-label" htmlFor="bet">YOUR BET</label><div className="chips">{[5,25,100].map(n=><button key={n} className={"chip chip-"+n+(bet===n?" selected":"")} onClick={()=>setBet(n)} disabled={!canBet||busy||n>balance} aria-label={"Bet "+n+" chips"} aria-pressed={bet===n}>{n}</button>)}<input id="bet" type="number" min="5" max={Math.min(500,Math.floor(balance))} step="1" value={bet} onChange={e=>setBet(Number(e.target.value))} disabled={!canBet||busy} aria-label="Custom bet"/></div></div>
 <div className="action-buttons">{canBet?<button className="primary deal-button" onClick={deal} disabled={busy||!Number.isInteger(bet)||bet<5||bet>500||bet>balance}>{busy?"Dealing…":state?.round?"Deal again":"Deal me in"}<ArrowUpRight size={18}/></button>:<><button className="primary" disabled={busy||!legal.includes("hit")} onClick={()=>act("hit")}>Hit <span>+</span></button><button disabled={busy||!legal.includes("stand")} onClick={()=>act("stand")}>Stand</button><button disabled={busy||!legal.includes("double")} onClick={()=>act("double")}>Double <span>×2</span></button></>}</div></div>
 {legal.includes("refill")&&<button className="refill" disabled={busy} onClick={()=>{setBet(25);void act("refill")}}><RotateCcw size={15}/> Refill play chips</button>}
 <div className="table-footer"><span>6 decks · 3:2 blackjack · No real money</span><span>{state?.wins??0} wins / {state?.hands??0} hands</span></div>
 {state?.history.length? <div className="history"><span className="control-label">RECENT HANDS</span><div>{state.history.slice(0,8).map(h=><span key={h.round} title={"Hand "+h.round+": "+h.player+" vs "+h.dealer} className={"history-result "+(h.profit>0?"positive":h.profit<0?"negative":"neutral")}>#{h.round} <b>{h.profit>0?"+":""}{chipFormat(h.profit)}</b></span>)}</div></div>:null}
 </div>
 <aside className="dealer-panel"><div className="dealer-heading"><div className="dealer-avatar">{isGrok?"G":"♠"}</div><div><p className="control-label">AT YOUR SERVICE</p><h2>{state?.dealerName??"House dealer"}</h2><p className="dealer-presence">{isGrok?(botRecent?"Checked the table just now":seen?"Connected · waiting for Grok":"Waiting for your bot"):"Ready to deal"}</p></div></div>
 <label className="mode-select"><span>Dealer</span><select aria-label="Choose dealer" value={state?.mode??"house"} disabled={busy} onChange={async e=>{const mode=e.target.value;if(!state&&!await act("create"))return;await act("mode",{mode});if(mode==="grok")void connect()}}><option value="house">House dealer</option><option value="grok">My Grok bot</option></select><ChevronDown size={15}/></label>
 <div className="chat-title"><MessageCircle size={15}/><h3>Table talk</h3><span>YOU + YOUR DEALER</span></div>
 <div className="chat-log" ref={log} role="log" aria-label="Table chat" aria-live="polite" aria-relevant="additions">{state?.messages.length?state.messages.map(m=>m.role==="system"?<p className="system-message" key={m.id}>{m.text}</p>:<div key={m.id} className={"chat-message "+m.role}><span>{m.name}</span><p>{m.text}</p></div>):<><div className="chat-message dealer"><span>House dealer</span><p>Pull up a chair. Choose your chips and I’ll deal you in.</p></div><div className="chat-welcome"><Spade size={25}/><p>A seat for you.<br/>A seat for your favorite bot.</p><button className="text-button" onClick={connect}>Connect Grok <ArrowUpRight size={14}/></button></div></>}</div>
 {isGrok&&<p className="chat-hint">After a move or message, say <b>“Continue”</b> in Grok. Your bot can then check the table and reply here.</p>}
 <form className="chat-form" onSubmit={async e=>{e.preventDefault();if(!draft.trim())return;if(!state&&!await act("create"))return;if(await act("chat",{message:draft}))setDraft("")}}><input aria-label="Message your dealer" placeholder="Say something to your dealer…" maxLength={1000} value={draft} onChange={e=>setDraft(e.target.value)}/><button type="submit" className="primary" aria-label="Send message" disabled={busy||!draft.trim()}><ArrowUp size={18}/></button></form>
 <p className="chat-footnote">{isGrok?"Grok replies appear here when it uses the connector.":"Connect your Grok bot for conversation at the table."}</p>
 </aside></section>
 <footer className="page-footer"><span>Stay for one more hand.</span><button className="text-button" onClick={connect}><Plug size={14}/> Connect a dealer</button></footer>
 <dialog ref={dialog} className="modal" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><div className="modal-header"><div><p className="eyebrow">{modal==="rules"?"THE HOUSE RULES":"SAVE YOUR BOT A SEAT"}</p><h2>{modal==="rules"?"Know your hand.":"Connect your Grok dealer"}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={22}/></button></div>
 {modal==="rules"?<div className="rules-content"><p>Get closer to 21 than the dealer without going over. Aces count as 1 or 11; face cards count as 10.</p><dl><div><dt>Blackjack</dt><dd>Two-card 21 pays 3:2. Both blackjack? Push.</dd></div><div><dt>Dealer</dt><dd>Hits below 17. Stands on every 17, including soft 17.</dd></div><div><dt>Double down</dt><dd>Double your first bet, take one card, then stand.</dd></div><div><dt>The shoe</dt><dd>Six decks. Reshuffled between hands below 52 cards.</dd></div><div><dt>Bet limits</dt><dd>5–500 play chips per hand. Whole-chip starting bets.</dd></div><div><dt>This table</dt><dd>No splits, insurance, or surrender. Refill when below 5 chips.</dd></div></dl><p className="muted">Play chips have no cash value. Grok’s dialogue never changes the rules or cards.</p></div>:<><div className="tabs">{[["mcp","Grok connector"],["bridge","Copy & paste"],["api","HTTP API"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="mcp"?<div className="connection-content"><ol className="setup-steps"><li><b>Add this table to Grok.</b><p>Open <a href="https://grok.com/connectors" target="_blank" rel="noreferrer">Grok Connectors <ArrowUpRight size={13}/></a>, choose <b>New Connector → Custom</b>, and paste this URL.</p></li></ol><label className="control-label" htmlFor="connector">SECRET TABLE CONNECTOR</label><div className="copy-row"><input id="connector" readOnly value={connectorUrl} placeholder={connecting?"Creating your connector…":"Create a connector link"} onFocus={e=>e.target.select()}/><button onClick={()=>copy(connectorUrl,"url")} disabled={!connectorUrl}>{copied==="url"?<Check size={16}/>:<Copy size={16}/>} {copied==="url"?"Copied":"Copy"}</button></div><p className="small-note">This link gives dealer access to this table. Keep it between you and your bot. If no link is shown, use Replace link below; the old connector will stop working.</p><ol start={2} className="setup-steps"><li><b>Wake up your bot and invite it in.</b><p>Enable this connector in your Grok conversation, then paste these instructions.</p></li></ol><div className="prompt-card"><p>{instructions}</p><button onClick={()=>copy(instructions,"invite")}><Copy size={15}/>{copied==="invite"?"Copied":"Copy invitation"}</button></div><ol start={3} className="setup-steps"><li><b>Play here. Resume your dealer in Grok.</b><p>Your bot’s replies appear in Table talk. After you play or send a message, say “Continue” in Grok. MCP doesn’t wake the bot automatically.</p></li></ol><div className="connection-note"><Info size={17}/><span>The connector needs a publicly reachable site without a sign-in gate. A private preview supports playing and copy & paste; direct Grok access needs public hosting.</span></div><button className="text-button rotate" disabled={connecting} onClick={rotate}><RotateCcw size={14}/> Replace link & revoke the old one</button></div>
 :tab==="bridge"?<div className="connection-content"><p>Use any Grok conversation without connector setup. Select <b>My Grok bot</b> as dealer, copy the current turn, and paste Grok’s JSON reply here.</p><button disabled={!state||!isGrok} onClick={preparePrompt}><Copy size={15}/>{copied==="prompt"?"Turn copied":"Copy current turn for Grok"}</button>{bridgePrompt&&<details><summary>View copied turn</summary><textarea aria-label="Turn prompt" readOnly value={bridgePrompt}/></details>}<label htmlFor="reply">Grok’s reply</label><textarea id="reply" rows={6} value={bridge} onChange={e=>setBridge(e.target.value)} placeholder='{"gameId":"…","expectedRevision":0,"action":"say","message":"Let’s play."}'/><button className="primary" onClick={applyBridge} disabled={!bridge.trim()||busy||!isGrok}>Apply dealer reply</button><p className="small-note">Each turn is checked against the live table. Copy a new turn after any move or chat message.</p></div>
 :<div className="connection-content"><p>Use the same secret from your connector URL as a Bearer token. The API shares the live game state with the MCP connector.</p><pre>GET /api/dealer{"\n"}Authorization: Bearer YOUR_DEALER_TOKEN</pre><pre>{JSON.stringify({tool:"post_chat",arguments:{message:"Good luck!",expectedRevision:state?.revision??0}},null,2)}</pre><p>Send that JSON to <code>POST /api/dealer</code>. Tools: <code>get_table</code>, <code>join_table</code>, <code>dealer_action</code>, <code>post_chat</code>.</p><p>Read first. Use the returned revision on every action. A stale revision returns 409; read again before retrying.</p><a href="/api/docs" target="_blank" rel="noreferrer">Open API documentation <ArrowUpRight size={14}/></a></div>}</>}
 </dialog>
 </main>
}
